import MuscleCard from "@/components/list/muscle-groups/index";
import type {
  GetServerSideProps,
  NextPage,
  InferGetServerSidePropsType,
} from "next";
import Head from "next/head";
import { prisma } from "../server/db/client";
import { muscleGroupWithImages, muscleIndividual } from "@/types/muscleGroup";
const Home: NextPage<{
  muscleGroups: InferGetServerSidePropsType<typeof getServerSideProps>;
}> = ({ muscleGroups }) => {
  console.log(muscleGroups[0]);
  console.log("El tipo de musclegroup es", typeof muscleGroups);
  return (
    <>
      <Head>
        <title>Volume Landmarks - Reinassance Periodization</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl  leading-normal font-extrabold ">
          Renaissance Periodization Volume Landmarks
        </h1>
        <div className="grid grid-cols-12 justify-center items-center gap-4">
          {muscleGroups.map((muscle: muscleIndividual) => (
            <MuscleCard key={muscle.id} muscle={muscle} />
          ))}
        </div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const muscleGroups: muscleGroupWithImages = await prisma.muscleGroup.findMany(
    {
      include: {
        images: true,
      },
    }
  );

  return {
    props: {
      muscleGroups,
    },
  };
};
export default Home;
